version: "3.8"

networks:
  voip_net:
    driver: bridge
    
services:
  webrtc-ui:
    build:
      context: .                   # Dockerfile is in this directory
      dockerfile: Dockerfile
    container_name: webrtc-ui
    hostname: frontend.local
    networks:
      voip_net:
        aliases:
          - frontend.local
    restart: unless-stopped
    ports:
      - "8080:80"                  # HTTP
      - "8443:443"                 # HTTPS
    volumes:
      - ./nginx/certs:/etc/nginx/certs

